'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Formacion_Asignacion
    
    '''<summary>
    '''Header control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Header As Global.digitacion.Header
    
    '''<summary>
    '''Pnl_Message control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pnl_Message As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblmsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblmsg As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtcaso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtcaso As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Txt_fc_inicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Txt_fc_inicio As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Txt_fc_fin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Txt_fc_fin As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CheckBox_casos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox_casos As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''Btn_Buscar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btn_Buscar As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''Btn_buscar_todos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btn_buscar_todos As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''Drl_Prioridad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Drl_Prioridad As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Drl_Estado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Drl_Estado As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Txt_id_cargue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Txt_id_cargue As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtfcingn3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtfcingn3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Txt_npersonas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Txt_npersonas As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Btn_guardar_N_Personas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btn_guardar_N_Personas As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''Txt_estado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Txt_estado As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Drl_Lugar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Drl_Lugar As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Txt_Observacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Txt_Observacion As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txt_grupo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_grupo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Txt_Personas_asignar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Txt_Personas_asignar As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Lbl_N_Personas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lbl_N_Personas As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Drl_Auditor_Asignar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Drl_Auditor_Asignar As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Btn_Agregar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btn_Agregar As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''btn_crear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_crear As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''txt_modulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_modulo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Txt_Fecha_modulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Txt_Fecha_modulo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Pnl_ConsTk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pnl_ConsTk As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''Lbl_Cantidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lbl_Cantidad As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Dtg_Asignar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dtg_Asignar As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''lblcuenta1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblcuenta1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''dtggeneral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtggeneral As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''lblcuenta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblcuenta As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''dtg_seguim control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtg_seguim As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''Drl_Formador_Consulta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Drl_Formador_Consulta As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Btn_Buscar_Formador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btn_Buscar_Formador As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lblcuenta3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblcuenta3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Dtg_Formador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dtg_Formador As Global.System.Web.UI.WebControls.GridView
End Class
