'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Prueba001
    
    '''<summary>
    '''Header control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Header As Global.digitacion.Header
    
    '''<summary>
    '''Pnl_Message control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pnl_Message As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblmsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblmsg As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtfcingn3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtfcingn3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''drlingclaro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drlingclaro As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''btn_crear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_crear As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''Drl_Tipo_Solicitud control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Drl_Tipo_Solicitud As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Txt_Observacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Txt_Observacion As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txt_nuevo_ing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_nuevo_ing As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btn_nuevo_ing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_nuevo_ing As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''Lbl_fc_ingreso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lbl_fc_ingreso As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lbl_ing_r control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_ing_r As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Drl_estado_reg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Drl_estado_reg As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txt_Numero_Solic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Numero_Solic As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Drl_Respuesta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Drl_Respuesta As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Btn_Guardar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btn_Guardar As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lbl_estado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_estado As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Lbl_Caso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lbl_Caso As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Txt_obs_reg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Txt_obs_reg As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txt_Numero_grabaciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Numero_grabaciones As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtcaso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtcaso As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Txt_fc_inicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Txt_fc_inicio As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Txt_fc_fin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Txt_fc_fin As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Drl_Estado_Busca control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Drl_Estado_Busca As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Btn_Buscar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btn_Buscar As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''Btn_buscar_todos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btn_buscar_todos As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''btn_Exportar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Exportar As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''Lbl_Exportar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lbl_Exportar As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Drl_ing_busca control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Drl_ing_busca As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''CheckBox_casos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox_casos As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblcuenta2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblcuenta2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''dtg_seguim control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtg_seguim As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''lblcuenta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblcuenta As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''dtggeneral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtggeneral As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''dtg_exportar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtg_exportar As Global.System.Web.UI.WebControls.GridView
End Class
