'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class HelpDeskAsignacion
    
    '''<summary>
    '''Header control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Header As Global.digitacion.Header
    
    '''<summary>
    '''Pnl_Message control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pnl_Message As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblmsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblmsg As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TxtCod_Ticket_Consulta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtCod_Ticket_Consulta As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''drlEstados control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drlEstados As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''TxtFecha_Inicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtFecha_Inicio As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtFecha_Fin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtFecha_Fin As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''BtnConsulta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnConsulta As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''BtnActualizar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnActualizar As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''txt_cod_usu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_cod_usu As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''drlPrioridad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drlPrioridad As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''drlTecnico control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drlTecnico As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''CheckBoxTipificacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBoxTipificacion As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''drlCategoria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drlCategoria As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''CheckBoxPrioridad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBoxPrioridad As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''drlPrioridadUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drlPrioridadUpdate As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''TxtObservacionAsigna control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtObservacionAsigna As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''drlTipo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drlTipo As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''CheckBoxArea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBoxArea As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''drlAreaUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drlAreaUpdate As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''LblCod_HeplDeks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblCod_HeplDeks As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LblUsuarioReporta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblUsuarioReporta As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LblTema control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblTema As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LblTema1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblTema1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LblUsuarioReg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblUsuarioReg As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''BtnAsignarCaso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnAsignarCaso As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''LblFecha_Registro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblFecha_Registro As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LblPrioridad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblPrioridad As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LblObservacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblObservacion As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LblObservacion1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblObservacion1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LblEstado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblEstado As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Pnl_ConsTk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pnl_ConsTk As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblcuentaHelpDesk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblcuentaHelpDesk As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''dtggeneralHelpDesk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtggeneralHelpDesk As Global.System.Web.UI.WebControls.GridView
End Class
