'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class cambiestilo
    
    '''<summary>
    '''Header control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Header As Global.digitacion.Header
    
    '''<summary>
    '''Pnl_Message control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pnl_Message As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblmsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblmsg As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''drlclasificacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drlclasificacion As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''TxtSerialActivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtSerialActivo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''drlZonaActivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drlZonaActivo As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''TxtReferenciaActivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtReferenciaActivo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''drlresponsable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drlresponsable As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''drlEstadoActivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drlEstadoActivo As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Panel3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel3 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''TxtN_Acta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtN_Acta As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnRegistrarActivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRegistrarActivo As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''drlNombreActivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drlNombreActivo As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''drlSedeActivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drlSedeActivo As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''drlMarcaActivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drlMarcaActivo As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''TxtDescripcionActivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtDescripcionActivo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''drlsubResponsable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drlsubResponsable As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''AsF_Archivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AsF_Archivo As Global.AjaxControlToolkit.AsyncFileUpload
    
    '''<summary>
    '''btnRegistrarActivo0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRegistrarActivo0 As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''TxtNombre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtNombre As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Panel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''drlclasificacion0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drlclasificacion0 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''drlPertenece control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drlPertenece As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''btnRegistrarNuevo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRegistrarNuevo As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''RdbSeriall control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RdbSeriall As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''TxtSerialConsulta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtSerialConsulta As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Rdbresponsable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Rdbresponsable As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''drlresponsable0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drlresponsable0 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''RdbClasificacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RdbClasificacion As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''drlclasificacionconsulta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drlclasificacionconsulta As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Rdbmarca control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Rdbmarca As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''drlMarca control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drlMarca As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Rdbsub_responsable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Rdbsub_responsable As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''drlsub_responsable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drlsub_responsable As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''btnConsultarActivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnConsultarActivo As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''btnExportarActivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnExportarActivo As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''RdbZona control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RdbZona As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''drlZona control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drlZona As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Rdbcodres control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Rdbcodres As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''drlcodresponsable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drlcodresponsable As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''RdbActivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RdbActivo As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''drlNombreActivo0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drlNombreActivo0 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''drlReferencia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drlReferencia As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''RdbN_ActaC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RdbN_ActaC As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''TxtN_ActaC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtN_ActaC As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Pnl_ConsTk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pnl_ConsTk As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''LblCantidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblCantidad As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''dtgInvt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtgInvt As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''dtgxls control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtgxls As Global.System.Web.UI.WebControls.GridView
End Class
