'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class RRHH_PruebasAsp
    
    '''<summary>
    '''Header control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Header As Global.digitacion.Header
    
    '''<summary>
    '''LblDato control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblDato As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Pnl_Message control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pnl_Message As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblmsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblmsg As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Pnl_DatosAspirante control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pnl_DatosAspirante As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''TxtDocAspActual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtDocAspActual As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Lbl_fkAspirante control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lbl_fkAspirante As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TxtNombresAspActual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtNombresAspActual As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Pnl_IniciarPrueba control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pnl_IniciarPrueba As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''TxtConsultaDoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtConsultaDoc As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''BtnIniciarPrueba control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnIniciarPrueba As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''Pnl_Prueba1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pnl_Prueba1 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''Lbl_Registro_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lbl_Registro_1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TxtCod_P1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtCod_P1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtNombre_P1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtNombre_P1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtCedula_P1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtCedula_P1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtDireccion_P1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtDireccion_P1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtEmail_P1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtEmail_P1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Btn_Siguiente_P1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btn_Siguiente_P1 As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''BtnComenzar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnComenzar As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''TxtEmpresa_P1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtEmpresa_P1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtCargo_P1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtCargo_P1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtTElefono_P1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtTElefono_P1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtDespacho_P1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtDespacho_P1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtNit_P1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtNit_P1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Pnl_Prueba2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pnl_Prueba2 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''TxtCod_P2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtCod_P2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtNombre_P2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtNombre_P2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtCedula_P2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtCedula_P2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtDireccion_P2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtDireccion_P2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtEmail_P2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtEmail_P2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Btn_Siguiente_P2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btn_Siguiente_P2 As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''TxtEmpresa_P2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtEmpresa_P2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtCargo_P2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtCargo_P2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtTElefono_P2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtTElefono_P2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtDespacho_P2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtDespacho_P2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtNit_P2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtNit_P2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Pnl_Prueba3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pnl_Prueba3 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''TxtCod_P3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtCod_P3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtNombre_P3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtNombre_P3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtCedula_P3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtCedula_P3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtDireccion_P3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtDireccion_P3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtEmail_P3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtEmail_P3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Btn_Siguiente_P3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btn_Siguiente_P3 As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''TxtEmpresa_P3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtEmpresa_P3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtCargo_P3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtCargo_P3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtTElefono_P3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtTElefono_P3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtDespacho_P3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtDespacho_P3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtNit_P3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtNit_P3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Pnl_Prueba4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pnl_Prueba4 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''TxtCod_P4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtCod_P4 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtNombre_P4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtNombre_P4 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtCedula_P4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtCedula_P4 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtDireccion_P4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtDireccion_P4 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtEmail_P4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtEmail_P4 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Btn_Siguiente_P4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btn_Siguiente_P4 As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''TxtEmpresa_P4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtEmpresa_P4 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtCargo_P4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtCargo_P4 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtTElefono_P4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtTElefono_P4 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtDespacho_P4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtDespacho_P4 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtNit_P4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtNit_P4 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Pnl_Prueba5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pnl_Prueba5 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''TxtCod_P5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtCod_P5 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtNombre_P5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtNombre_P5 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtCedula_P5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtCedula_P5 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtDireccion_P5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtDireccion_P5 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtEmail_P5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtEmail_P5 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Btn_FinalizarPrueba control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btn_FinalizarPrueba As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''Btn_Regresar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btn_Regresar As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''TxtEmpresa_P5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtEmpresa_P5 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtCargo_P5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtCargo_P5 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtTElefono_P5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtTElefono_P5 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtDespacho_P5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtDespacho_P5 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TxtNit_P5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtNit_P5 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''countdown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents countdown As Global.System.Web.UI.WebControls.Label
End Class
