'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Dilo2
    
    '''<summary>
    '''Lbl_Enun_Desp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lbl_Enun_Desp As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Pnl_Msg_Desp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pnl_Msg_Desp As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''Lbl_Msg_Desp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lbl_Msg_Desp As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Btn_ConfimrDialog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btn_ConfimrDialog As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''Btn_Back_Desp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btn_Back_Desp As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''Header control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Header As Global.digitacion.Header
    
    '''<summary>
    '''Pnl_Message control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pnl_Message As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblmsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblmsg As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtcaso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtcaso As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Btn_Consultar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btn_Consultar As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblescalamiento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblescalamiento As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblfcreporte control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblfcreporte As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbltelcontacto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbltelcontacto As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblequipo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblequipo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbltipofalla control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbltipofalla As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblmesa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblmesa As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblbarrio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblbarrio As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Lblfc_ingreso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lblfc_ingreso As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbl_canal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_canal As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblmin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblmin As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblcliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblcliente As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbltecnologia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbltecnologia As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblestado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblestado As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblsolicitud control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblsolicitud As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblcaso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblcaso As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblNumero_Alterno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNumero_Alterno As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnguardar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnguardar As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''drldpto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drldpto As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtbarrio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbarrio As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Btn_Act_Barrio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btn_Act_Barrio As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''drlsolicita_ajuste control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drlsolicita_ajuste As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''drlmun control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drlmun As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Btn_Act_Mun control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btn_Act_Mun As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''CompareValidator3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CompareValidator3 As Global.System.Web.UI.WebControls.CompareValidator
    
    '''<summary>
    '''telefono control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents telefono As Global.System.Web.UI.WebControls.RegularExpressionValidator
    
    '''<summary>
    '''chkSi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSi As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''chkNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkNo As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''txtnumalt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtnumalt As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''drllinea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drllinea As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''drlsolicitud control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drlsolicitud As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''drlSegmento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drlSegmento As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''drlservicio2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drlservicio2 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''drlModalidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drlModalidad As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''drlCausa_Raiz control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drlCausa_Raiz As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''drltipificacionll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drltipificacionll As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''CV_PQR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CV_PQR As Global.System.Web.UI.WebControls.CompareValidator
    
    '''<summary>
    '''LblPQR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblPQR As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TxtPQR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtPQR As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Panel_Justificacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_Justificacion As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''Drl_justificacion_seguimiento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Drl_justificacion_seguimiento As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Pnl_Estacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pnl_Estacion As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''txt_Estacion_base control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Estacion_base As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''drlCategoriaCierre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drlCategoriaCierre As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''drlTipo_PQR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drlTipo_PQR As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Btn_Act_PQR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btn_Act_PQR As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''Pnl_Tipo_canal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pnl_Tipo_canal As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''drl_tipo_canal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drl_tipo_canal As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Pnl_Seguimiento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pnl_Seguimiento As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''txtfc_programado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtfc_programado As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''drlLibera control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drlLibera As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''drldpto_incon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drldpto_incon As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Txt_Distribuidor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Txt_Distribuidor As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Btn_Actualizar_Distribuidor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btn_Actualizar_Distribuidor As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''drlmun_incon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drlmun_incon As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Btn_Actualizar_Mun_Distri control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btn_Actualizar_Mun_Distri As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''txtobs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtobs As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pnservice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnservice As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''drlapn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drlapn As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''drlqos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drlqos As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Lbl_Title control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lbl_Title As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''drlvariable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drlvariable As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''AsF_Archivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AsF_Archivo As Global.AjaxControlToolkit.AsyncFileUpload
    
    '''<summary>
    '''txtfcactivacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtfcactivacion As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rdbron control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdbron As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''drlArea_Aplica control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drlArea_Aplica As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblvariable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblvariable As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''PNEscalam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PNEscalam As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''txtFcontacto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFcontacto As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''drlFtiempo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drlFtiempo As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''drlFcaract control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drlFcaract As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtFciudad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFciudad As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtFdirecc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFdirecc As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''drlmarca control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drlmarca As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtapn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtapn As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''drlFlineasfalla control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drlFlineasfalla As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''DrlCanalDilo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DrlCanalDilo As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''CV_Txt_N_Doc_Id_CPD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CV_Txt_N_Doc_Id_CPD As Global.System.Web.UI.WebControls.CompareValidator
    
    '''<summary>
    '''RFV_Txt_N_Doc_Id_CPD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RFV_Txt_N_Doc_Id_CPD As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''Txt_N_Doc_Id_CPD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Txt_N_Doc_Id_CPD As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtFnum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFnum As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtFtipofalla control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFtipofalla As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''drlFportada control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drlFportada As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''rdbvc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdbvc As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''drlFtectolog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drlFtectolog As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblctrl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblctrl As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''drlequipo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drlequipo As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Drl_Qos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Drl_Qos As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtfobs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtfobs As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Drl_Falla_Presenta_Luego_Construyera_Edificacion_Aledania control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Drl_Falla_Presenta_Luego_Construyera_Edificacion_Aledania As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Drl_Tipo_Edificacion_Donde_Presenta_Falla_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Drl_Tipo_Edificacion_Donde_Presenta_Falla_1 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Drl_Tipo_Edificacion_Donde_Presenta_Falla_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Drl_Tipo_Edificacion_Donde_Presenta_Falla_2 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Drl_Tecnologia_Presenta_Falla_Luegodepruebas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Drl_Tecnologia_Presenta_Falla_Luegodepruebas As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Drl_Linea_No_Cuenta_Bloqueos_Internet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Drl_Linea_No_Cuenta_Bloqueos_Internet As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Drl_Linea_No_Encuentra_Enrutada_PorPagos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Drl_Linea_No_Encuentra_Enrutada_PorPagos As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Drl_No_Existen_Cambios_Administrativos_Sobre_Linea_Cuenta_Maestra control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Drl_No_Existen_Cambios_Administrativos_Sobre_Linea_Cuenta_Maestra As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Drl_Split_Billing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Drl_Split_Billing As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Drl_Forza_Red_Dispositivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Drl_Forza_Red_Dispositivo As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Drl_Equipo_Encuentra_Homologado_Operador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Drl_Equipo_Encuentra_Homologado_Operador As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Drl_Falla_Presenta_Luego_Remodelara_Estructura_Fisica_Edificio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Drl_Falla_Presenta_Luego_Remodelara_Estructura_Fisica_Edificio As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Drl_Validaciones_Falla_Masiva control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Drl_Validaciones_Falla_Masiva As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Txt_Validacion_Coordenadas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Txt_Validacion_Coordenadas As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Drl_Linea_No_Superado_Limite_Consumos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Drl_Linea_No_Superado_Limite_Consumos As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Drl_HLR_HSS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Drl_HLR_HSS As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Drl_Realizan_Pruebas_SIMCARD_OtroDispositivo_PersisteFalla control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Drl_Realizan_Pruebas_SIMCARD_OtroDispositivo_PersisteFalla As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Drl_Verifica_Realiza_Configuración_APN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Drl_Verifica_Realiza_Configuración_APN As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Drl_Realiza_Conciliacion_Sobre_linea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Drl_Realiza_Conciliacion_Sobre_linea As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''LinkButton3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkButton3 As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''LinkButton4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkButton4 As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''Pninc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pninc As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''RegularExpressionValidator1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RegularExpressionValidator1 As Global.System.Web.UI.WebControls.RegularExpressionValidator
    
    '''<summary>
    '''Txt_custcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Txt_custcode As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''drlinconsglobal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drlinconsglobal As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''drlnivel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drlnivel As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Txt_usuario_reporta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Txt_usuario_reporta As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''drlincons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drlincons As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''drl_ubicacion_call control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drl_ubicacion_call As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtobsinc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtobsinc As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnguardar0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnguardar0 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''Pnl_CasAsig control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pnl_CasAsig As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblcasos_asig control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblcasos_asig As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''dtgprog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtgprog As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''Pnl_CasGest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pnl_CasGest As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblcuenta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblcuenta As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''dtggeneral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtggeneral As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''Pnl_MenuRight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pnl_MenuRight As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''Check_NokmUsu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Check_NokmUsu As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''Check_Min control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Check_Min As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''Check_FallakVCli control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Check_FallakVCli As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''Check_UbkiCli control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Check_UbkiCli As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''Check_EqukiUso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Check_EqukiUso As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''Check_TiemFkalla control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Check_TiemFkalla As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''Check_PlankActi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Check_PlankActi As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''Check_ConfCokrreo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Check_ConfCokrreo As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''Check_LiknAlt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Check_LiknAlt As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''Check_Conksumo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Check_Conksumo As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''Check_PerkfSim control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Check_PerkfSim As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''Check_QDN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Check_QDN As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''Check_QOS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Check_QOS As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''Check_ValkUSIM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Check_ValkUSIM As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''Check_ProkcSop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Check_ProkcSop As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''Check_PrukeRel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Check_PrukeRel As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''Check_ReskGest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Check_ReskGest As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''Check_InfAkdUsu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Check_InfAkdUsu As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''Check_EstFiknCas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Check_EstFiknCas As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''Check_LeckTerm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Check_LeckTerm As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''Btn_limpiar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btn_limpiar As Global.System.Web.UI.WebControls.Button
End Class
